version: 0.0
Resources:
  - test: # Replace "MyFunction" with the name of your Lambda function
      Type: AWS::Lambda::Function
      Properties:
        Name: "zeno-cicd" # Specify the name of your Lambda function
        Alias: "v2" # Specify the alias for your Lambda function
        CurrentVersion: "v1" # Specify the current version of your Lambda function
        TargetVersion: "v2" # Specify the version of your Lambda function to deploy
